export const  MISSION_DATABASE = [
    // ============ MISSÕES EXISTENTES (24) ============
    { title: "Círculo de Fogo", description: "Atividade sísmica e vulcânica intensa no arquipélago japonês.", lat: 36.2, lng: 138.2, tags: ["Sismo", "Ásia"], precision: 600000, hint: "Costa leste da Ásia, entre o Pacífico e o Mar do Japão." },
    { title: "Amazônia", description: "Planície sedimentar equatorial com a maior bacia hidrográfica do mundo.", lat: -3.4, lng: -62.2, tags: ["Bio", "Brasil"], precision: 800000, hint: "Norte da América do Sul, região de selva densa." },
    { title: "Vale do Nilo", description: "Rio alóctone que atravessa o deserto, permitindo a vida no Egito.", lat: 30.0, lng: 31.2, tags: ["H2O", "África"], precision: 500000, hint: "Nordeste da África, desembocando no Mediterrâneo." },
    { title: "Himalaia", description: "Dobramento moderno no centro da Ásia, onde fica o Monte Everest.", lat: 27.9, lng: 86.9, tags: ["Relevo", "Ásia"], precision: 600000, hint: "Norte do subcontinente indiano." },
    { title: "Meridiano Zero", description: "Londres, o marco inicial dos fusos horários mundiais.", lat: 51.5, lng: -0.1, tags: ["Carto", "Europa"], precision: 300000, hint: "Capital britânica, sudeste da ilha." },
    { title: "Saara", description: "O maior domínio morfoclimático árido do planeta.", lat: 23.4, lng: 12.6, tags: ["Árido", "África"], precision: 1200000, hint: "Cobre quase todo o terço norte da África." },
    { title: "Vale do Silício", description: "Epicentro da inovação e tecnologia global.", lat: 37.4, lng: -122.0, tags: ["Tech", "EUA"], precision: 400000, hint: "Califórnia, próximo a San Francisco." },
    { title: "Barreira de Corais", description: "Estrutura biológica colossal na costa da Austrália.", lat: -18.2, lng: 147.7, tags: ["Eco", "Oceania"], precision: 800000, hint: "Mar de Coral, nordeste australiano." },
    { title: "Brasília", description: "A capital modernista projetada em formato de avião.", lat: -15.7975, lng: -47.8919, tags: ["Capital", "Brasil"], precision: 50000, hint: "Planalto Central brasileiro." },
    { title: "Tóquio", description: "A metrópole mais populosa do mundo e centro tecnológico.", lat: 35.6762, lng: 139.6503, tags: ["Capital", "Ásia"], precision: 80000, hint: "Ilha de Honshu, Japão." },
    { title: "Paris", description: "A Cidade Luz, cortada pelo Rio Sena.", lat: 48.8566, lng: 2.3522, tags: ["Capital", "Europa"], precision: 60000, hint: "Norte da França." },
    { title: "Londres", description: "Sede da monarquia britânica e do Big Ben.", lat: 51.5074, lng: -0.1278, tags: ["Capital", "Europa"], precision: 60000, hint: "Sudeste da Ilha da Grã-Bretanha." },
    { title: "Washington D.C.", description: "Centro do poder político dos Estados Unidos.", lat: 38.9072, lng: -77.0369, tags: ["Capital", "EUA"], precision: 70000, hint: "Costa leste americana, Distrito de Columbia." },
    { title: "Camberra", description: "Capital planejada da Oceania.", lat: -35.2809, lng: 149.1300, tags: ["Capital", "Oceania"], precision: 90000, hint: "Sudeste da Austrália." },
    { title: "Moscou", description: "O coração da Rússia, onde fica o Kremlin.", lat: 55.7558, lng: 37.6173, tags: ["Capital", "Ásia"], precision: 100000, hint: "Leste europeu/Rússia ocidental." },
    { title: "Pequim", description: "A capital imperial e moderna da China.", lat: 39.9042, lng: 116.4074, tags: ["Capital", "Ásia"], precision: 100000, hint: "Norte da China." },
    { title: "Salvador", description: "Primeira capital do Brasil e sede do Geo-Command.", lat: -12.9777, lng: -38.5016, tags: ["Bahia", "Brasil"], precision: 30000, hint: "Baía de Todos os Santos." },
    { title: "Feira de Santana", description: "A Princesa do Sertão, maior entroncamento rodoviário do Norte/Nordeste.", lat: -12.2733, lng: -38.9556, tags: ["Bahia", "Logística"], precision: 40000, hint: "Portal do sertão baiano." },
    { title: "Vitória da Conquista", description: "A Suíça Baiana, conhecida pelo seu clima frio no sertão.", lat: -14.8661, lng: -40.8394, tags: ["Bahia", "Brasil"], precision: 45000, hint: "Sudoeste da Bahia." },
    { title: "Ilhéus", description: "Terra do cacau e cenário das obras de Jorge Amado.", lat: -14.7889, lng: -39.0494, tags: ["Bahia", "Litoral"], precision: 35000, hint: "Sul da Bahia." },
    { title: "Porto Seguro", description: "Onde as caravelas de Cabral avistaram terra firme.", lat: -16.4497, lng: -39.0641, tags: ["Bahia", "História"], precision: 40000, hint: "Costa do Descobrimento." },
    { title: "Pirâmides de Gizé", description: "As tumbas monumentais dos faraós do Egito Antigo.", lat: 29.9792, lng: 31.1342, tags: ["História", "África"], precision: 150000, hint: "Margem esquerda do Nilo." },
    { title: "Machu Picchu", description: "A cidade perdida dos Incas no topo dos Andes.", lat: -13.1631, lng: -72.5450, tags: ["História", "América"], precision: 120000, hint: "Cordilheira dos Andes, Peru." },
    { title: "Grande Barreira de Corais", description: "O maior organismo vivo da Terra, visível do espaço.", lat: -18.2871, lng: 147.6992, tags: ["Natureza", "Oceania"], precision: 500000, hint: "Mar de Coral, Austrália." },
    { title: "Monte Everest", description: "O ponto mais alto da crosta terrestre.", lat: 27.9881, lng: 86.9250, tags: ["Geografia", "Ásia"], precision: 200000, hint: "Cordilheira do Himalaia, fronteira Nepal-China." },
    { title: "Canal do Panamá", description: "A ligação estratégica entre o Atlântico e o Pacífico.", lat: 9.1185, lng: -79.6867, tags: ["Estratégico", "Logística"], precision: 100000, hint: "América Central." },
    { title: "Estreito de Gibraltar", description: "Onde o Mediterrâneo encontra o Oceano Atlântico.", lat: 35.9375, lng: -5.4640, tags: ["Militar", "Europa"], precision: 150000, hint: "Fronteira Espanha-Marrocos." },
    { title: "Ilha de Páscoa", description: "Famosa pelas estátuas gigantes de pedra chamadas Moai.", lat: -27.1127, lng: -109.3497, tags: ["Mistério", "Polinésia"], precision: 200000, hint: "Pacífico Sul, território chileno." },

    // ============ CAPITAIS DO MUNDO (30) ============
    { title: "Roma", description: "Cidade Eterna, antigo coração do Império Romano.", lat: 41.9028, lng: 12.4964, tags: ["Capital", "Europa"], precision: 50000, hint: "Itália, península itálica." },
    { title: "Berlim", description: "Capital reunificada da Alemanha, símbolo da Guerra Fria.", lat: 52.5200, lng: 13.4050, tags: ["Capital", "Europa"], precision: 50000, hint: "Nordeste da Alemanha." },
    { title: "Madri", description: "Capital da Espanha, localizada no centro do país.", lat: 40.4168, lng: -3.7038, tags: ["Capital", "Europa"], precision: 60000, hint: "Planície central da Espanha." },
    { title: "Lisboa", description: "Capital portuguesa construída sobre sete colinas.", lat: 38.7223, lng: -9.1393, tags: ["Capital", "Europa"], precision: 40000, hint: "Foz do rio Tejo." },
    { title: "Buenos Aires", description: "Capital da Argentina, terra do tango.", lat: -34.6037, lng: -58.3816, tags: ["Capital", "América"], precision: 60000, hint: "Margem do Rio da Prata." },
    { title: "Santiago", description: "Capital chilena aos pés da Cordilheira dos Andes.", lat: -33.4489, lng: -70.6693, tags: ["Capital", "América"], precision: 70000, hint: "Vale central do Chile." },
    { title: "Lima", description: "Capital do Peru, fundada por conquistadores espanhóis.", lat: -12.0464, lng: -77.0428, tags: ["Capital", "América"], precision: 80000, hint: "Costa central do Peru." },
    { title: "Bogotá", description: "Capital da Colômbia em um altiplano andino.", lat: 4.7110, lng: -74.0721, tags: ["Capital", "América"], precision: 70000, hint: "Cordilheira Oriental dos Andes." },
    { title: "Cidade do México", description: "Capital construída sobre o antigo lago Texcoco.", lat: 19.4326, lng: -99.1332, tags: ["Capital", "América"], precision: 80000, hint: "Vale do México, altiplano central." },
    { title: "Ottawa", description: "Capital do Canadá na fronteira entre Ontario e Quebec.", lat: 45.4215, lng: -75.6972, tags: ["Capital", "América"], precision: 60000, hint: "Margem do rio Ottawa." },
    { title: "Nova Delhi", description: "Capital da Índia, projeto urbanístico britânico.", lat: 28.6139, lng: 77.2090, tags: ["Capital", "Ásia"], precision: 80000, hint: "Norte da Índia, metrópole de Delhi." },
    { title: "Bangkok", description: "Capital da Tailândia, cidade dos templos dourados.", lat: 13.7563, lng: 100.5018, tags: ["Capital", "Ásia"], precision: 70000, hint: "Delta do rio Chao Phraya." },
    { title: "Jakarta", description: "Capital da Indonésia na ilha de Java.", lat: -6.2088, lng: 106.8456, tags: ["Capital", "Ásia"], precision: 90000, hint: "Costa noroeste de Java." },
    { title: "Seul", description: "Capital tecnológica da Coreia do Sul.", lat: 37.5665, lng: 126.9780, tags: ["Capital", "Ásia"], precision: 60000, hint: "Margem do rio Han." },
    { title: "Cairo", description: "Capital do Egito, próxima às pirâmides.", lat: 30.0444, lng: 31.2357, tags: ["Capital", "África"], precision: 80000, hint: "Margem leste do Nilo." },
    { title: "Nairóbi", description: "Capital do Quênia e centro econômico da África Oriental.", lat: -1.2864, lng: 36.8172, tags: ["Capital", "África"], precision: 70000, hint: "Terras altas do Quênia." },
    { title: "Pretória", description: "Capital administrativa da África do Sul.", lat: -25.7479, lng: 28.2293, tags: ["Capital", "África"], precision: 60000, hint: "Província de Gauteng." },
    { title: "Cidade do Cabo", description: "Capital legislativa da África do Sul.", lat: -33.9249, lng: 18.4241, tags: ["Capital", "África"], precision: 60000, hint: "Costa sudoeste, Cabo da Boa Esperança." },
    { title: "Wellington", description: "Capital da Nova Zelândia, na ponta sul da Ilha do Norte.", lat: -41.2865, lng: 174.7762, tags: ["Capital", "Oceania"], precision: 50000, hint: "Estreito de Cook." },
    { title: "Suva", description: "Capital de Fiji, no Pacífico Sul.", lat: -18.1248, lng: 178.4501, tags: ["Capital", "Oceania"], precision: 40000, hint: "Ilha de Viti Levu." },
    { title: "Havana", description: "Capital de Cuba, famosa por seus charutos e carros antigos.", lat: 23.1136, lng: -82.3666, tags: ["Capital", "América"], precision: 50000, hint: "Costa noroeste de Cuba." },
    { title: "Caracas", description: "Capital da Venezuela em um vale montanhoso.", lat: 10.4806, lng: -66.9036, tags: ["Capital", "América"], precision: 70000, hint: "Norte da Venezuela, próximo ao Caribe." },
    { title: "Montevidéu", description: "Capital do Uruguai, na margem do Rio da Prata.", lat: -34.9011, lng: -56.1645, tags: ["Capital", "América"], precision: 50000, hint: "Margem sul do Rio da Prata." },
    { title: "La Paz", description: "Sede de governo da Bolívia, a capital mais alta do mundo.", lat: -16.4897, lng: -68.1193, tags: ["Capital", "América"], precision: 70000, hint: "Cordilheira dos Andes, altiplano." },
    { title: "Quito", description: "Capital do Equador, a segunda capital mais alta do mundo.", lat: -0.1807, lng: -78.4678, tags: ["Capital", "América"], precision: 60000, hint: "Vale andino, próximo ao vulcão Pichincha." },
    { title: "Teerã", description: "Capital do Irã, aos pés das montanhas Alborz.", lat: 35.6892, lng: 51.3890, tags: ["Capital", "Ásia"], precision: 90000, hint: "Norte do Irã." },
    { title: "Ancara", description: "Capital da Turquia, no planalto da Anatólia.", lat: 39.9334, lng: 32.8597, tags: ["Capital", "Ásia"], precision: 70000, hint: "Região central da Turquia." },
    { title: "Bagdá", description: "Capital do Iraque, histórica cidade às margens do Tigre.", lat: 33.3152, lng: 44.3661, tags: ["Capital", "Ásia"], precision: 90000, hint: "Margem do rio Tigre." },
    { title: "Cabul", description: "Capital do Afeganistão em um vale montanhoso.", lat: 34.5553, lng: 69.2075, tags: ["Capital", "Ásia"], precision: 80000, hint: "Vale do rio Cabul." },
    { title: "Islamabad", description: "Capital planejada do Paquistão.", lat: 33.6844, lng: 73.0479, tags: ["Capital", "Ásia"], precision: 70000, hint: "Pés das colinas Margalla." },

    // ============ MARAVILHAS NATURAIS (30) ============
    { title: "Grand Canyon", description: "Garganta colossal esculpida pelo Rio Colorado.", lat: 36.0544, lng: -112.1401, tags: ["Natureza", "EUA"], precision: 200000, hint: "Arizona, sudoeste dos EUA." },
    { title: "Cataratas do Iguaçu", description: "Conjunto de 275 quedas d'água na fronteira Brasil-Argentina.", lat: -25.6953, lng: -54.4367, tags: ["Natureza", "Brasil"], precision: 150000, hint: "Fronteira entre Paraná (BR) e Misiones (AR)." },
    { title: "Monte Fuji", description: "Vulcão adormecido e símbolo sagrado do Japão.", lat: 35.3606, lng: 138.7274, tags: ["Vulcão", "Ásia"], precision: 100000, hint: "Ilha de Honshu, sudoeste de Tóquio." },
    { title: "Aurora Boreal", description: "Fenômeno de luzes no céu noturno próximo ao Ártico.", lat: 69.6825, lng: 18.9578, tags: ["Fenômeno", "Ártico"], precision: 1000000, hint: "Círculo Polar Ártico, visível na Noruega." },
    { title: "Lago Baikal", description: "O lago mais profundo e antigo do mundo.", lat: 53.5586, lng: 108.1773, tags: ["Lago", "Rússia"], precision: 300000, hint: "Sibéria, sul da Rússia." },
    { title: "Deserto do Atacama", description: "O deserto mais seco do planeta.", lat: -23.5, lng: -69.0, tags: ["Árido", "Chile"], precision: 400000, hint: "Norte do Chile, costa do Pacífico." },
    { title: "Pantanal", description: "Maior planície inundável do mundo.", lat: -17.95, lng: -57.5, tags: ["Bio", "Brasil"], precision: 400000, hint: "Centro-oeste do Brasil, fronteira com Bolívia/Paraguai." },
    { title: "Fiordes Noruegueses", description: "Vales glaciais inundados pelo mar.", lat: 60.9405, lng: 6.9570, tags: ["Geologia", "Europa"], precision: 300000, hint: "Costa oeste da Noruega." },
    { title: "Kalahari", description: "Grande deserto arenoso no sul da África.", lat: -23.0, lng: 22.0, tags: ["Árido", "África"], precision: 800000, hint: "Botsuana, Namíbia, África do Sul." },
    { title: "Serengeti", description: "Savana famosa pela migração anual de gnus.", lat: -2.3333, lng: 34.8333, tags: ["Bio", "África"], precision: 500000, hint: "Tanzânia e Quênia." },
    { title: "Salto Ángel", description: "Maior queda d'água ininterrupta do mundo.", lat: 5.9706, lng: -62.5362, tags: ["Natureza", "Venezuela"], precision: 200000, hint: "Parque Nacional Canaima, sudeste da Venezuela." },
    { title: "Arquipélago de Galápagos", description: "Ilhas vulcânicas que inspiraram Darwin.", lat: -0.7773, lng: -91.1426, tags: ["Bio", "Equador"], precision: 200000, hint: "Oceano Pacífico, a oeste do Equador continental." },
    { title: "Monte Kilimanjaro", description: "Montanha mais alta da África, vulcão adormecido.", lat: -3.0674, lng: 37.3556, tags: ["Montanha", "África"], precision: 150000, hint: "Tanzânia, próximo à fronteira com o Quênia." },
    { title: "Great Blue Hole", description: "Grande dolina submarina na barreira de coral.", lat: 17.3159, lng: -87.5346, tags: ["Natureza", "Belize"], precision: 100000, hint: "Recife de Lighthouse, Belize." },
    { title: "Parque Nacional Yellowstone", description: "Primeiro parque nacional do mundo, famoso por seus gêiseres.", lat: 44.4280, lng: -110.5885, tags: ["Geotermal", "EUA"], precision: 300000, hint: "Principalmente em Wyoming, EUA." },
    { title: "Caverna de Son Doong", description: "Maior caverna do mundo por volume.", lat: 17.4594, lng: 106.2837, tags: ["Geologia", "Vietnã"], precision: 150000, hint: "Parque Nacional Phong Nha-Kẻ Bàng, Vietnã." },
    { title: "Uluru (Ayers Rock)", description: "Monólito sagrado de arenito vermelho.", lat: -25.3444, lng: 131.0369, tags: ["Sagrado", "Oceania"], precision: 100000, hint: "Território do Norte, Austrália." },
    { title: "Planalto do Tibete", description: "O 'teto do mundo', o maior e mais alto planalto.", lat: 33.0, lng: 88.0, tags: ["Relevo", "Ásia"], precision: 800000, hint: "Sul da China, norte do Himalaia." },
    { title: "Vale da Morte", description: "Um dos lugares mais quentes e secos da Terra.", lat: 36.5323, lng: -116.9325, tags: ["Árido", "EUA"], precision: 250000, hint: "Califórnia e Nevada, EUA." },
    { title: "Lago Titicaca", description: "Maior lago navegável do mundo em altitude.", lat: -15.9254, lng: -69.3354, tags: ["Lago", "América"], precision: 200000, hint: "Fronteira Peru-Bolívia, altiplano andino." },
    { title: "Delta do Okavango", description: "Delta interior que forma um oásis no deserto.", lat: -19.2833, lng: 22.9000, tags: ["Bio", "África"], precision: 350000, hint: "Botsuana, deserto do Kalahari." },
    { title: "Montanhas Rochosas", description: "Grande cordilheira no oeste da América do Norte.", lat: 44.0, lng: -110.0, tags: ["Relevo", "América"], precision: 600000, hint: "Do Canadá ao Novo México, EUA." },
    { title: "Bacia do Congo", description: "Segunda maior floresta tropical do mundo.", lat: 0.0, lng: 22.0, tags: ["Bio", "África"], precision: 900000, hint: "Centro da África, ao longo do equador." },
    { title: "Lago Ness", description: "Lago famoso por seu suposto monstro aquático.", lat: 57.3229, lng: -4.4244, tags: ["Lago", "Europa"], precision: 80000, hint: "Terras Altas da Escócia." },
    { title: "Monte Sinai", description: "Montanha sagrada onde Moisés recebeu os Dez Mandamentos.", lat: 28.5390, lng: 33.9750, tags: ["Sagrado", "África"], precision: 100000, hint: "Península do Sinai, Egito." },
    { title: "Parque Nacional Torres del Paine", description: "Famoso por seus picos de granito e geleiras.", lat: -51.2594, lng: -72.3450, tags: ["Natureza", "Chile"], precision: 200000, hint: "Patagônia chilena." },
    { title: "Deserto de Gobi", description: "Grande deserto da Ásia, famoso por seus fósseis de dinossauros.", lat: 43.5, lng: 105.0, tags: ["Árido", "Ásia"], precision: 700000, hint: "Norte da China e sul da Mongólia." },
    { title: "Geleira Perito Moreno", description: "Uma das poucas geleiras em avanço no mundo.", lat: -50.4833, lng: -73.0500, tags: ["Geleira", "Argentina"], precision: 150000, hint: "Parque Nacional Los Glaciares, Patagônia." },
    { title: "Monte Elbrus", description: "Ponto mais alto da Europa.", lat: 43.3550, lng: 42.4392, tags: ["Montanha", "Europa"], precision: 150000, hint: "Cáucaso, Rússia." },
    { title: "Cânion do Colca", description: "Um dos cânions mais profundos do mundo.", lat: -15.5978, lng: -71.8797, tags: ["Natureza", "Peru"], precision: 180000, hint: "Região de Arequipa, sul do Peru." },

    // ============ SÍTIOS HISTÓRICOS E ARQUEOLÓGICOS (30) ============
    { title: "Petra", description: "Cidade rosa esculpida em rocha pelos nabateus.", lat: 30.3285, lng: 35.4444, tags: ["História", "Ásia"], precision: 120000, hint: "Deserto da Jordânia." },
    { title: "Coliseu", description: "Anfiteatro romano onde ocorriam lutas de gladiadores.", lat: 41.8902, lng: 12.4922, tags: ["História", "Europa"], precision: 50000, hint: "Centro de Roma, Itália." },
    { title: "Acrópole de Atenas", description: "Cidadela sagrada dedicada à deusa Atena.", lat: 37.9715, lng: 23.7257, tags: ["História", "Europa"], precision: 60000, hint: "Colina no centro de Atenas, Grécia." },
    { title: "Muralha da China", description: "Grande muralha construída para defesa do império.", lat: 40.4319, lng: 116.5704, tags: ["História", "Ásia"], precision: 500000, hint: "Norte da China, serpenteia por montanhas." },
    { title: "Stonehenge", description: "Monumento megalítico do neolítico.", lat: 51.1789, lng: -1.8262, tags: ["Mistério", "Europa"], precision: 80000, hint: "Planície de Salisbury, sul da Inglaterra." },
    { title: "Angkor Wat", description: "Maior templo religioso do mundo.", lat: 13.4125, lng: 103.8670, tags: ["História", "Ásia"], precision: 150000, hint: "Siem Reap, noroeste do Camboja." },
    { title: "Ilha de Alcatraz", description: "Famosa prisão federal em uma ilha.", lat: 37.8267, lng: -122.4233, tags: ["História", "EUA"], precision: 30000, hint: "Baía de São Francisco, Califórnia." },
    { title: "Pompéia", description: "Cidade romana preservada por cinzas vulcânicas.", lat: 40.7510, lng: 14.4874, tags: ["História", "Europa"], precision: 70000, hint: "Sul da Itália, próximo ao Vesúvio." },
    { title: "Mesquita Azul", description: "Mesquita histórica com seis minaretes.", lat: 41.0054, lng: 28.9768, tags: ["História", "Ásia"], precision: 40000, hint: "Istambul, Turquia." },
    { title: "Taj Mahal", description: "Mausoléu de mármore branco construído por um imperador.", lat: 27.1751, lng: 78.0421, tags: ["História", "Ásia"], precision: 80000, hint: "Agra, Índia, margem do rio Yamuna." },
    { title: "Esterilizador de Cuzco", description: "Capital histórica do Império Inca.", lat: -13.5319, lng: -71.9675, tags: ["História", "América"], precision: 70000, hint: "Vale andino no sul do Peru." },
    { title: "Ilha de Robben", description: "Prisão onde Nelson Mandela foi mantido.", lat: -33.8069, lng: 18.3712, tags: ["História", "África"], precision: 40000, hint: "Baía da Mesa, Cidade do Cabo, África do Sul." },
    { title: "Estatuária da Ilha de Páscoa", description: "Moais, estátuas monolíticas de pedra.", lat: -27.1127, lng: -109.3497, tags: ["Mistério", "Polinésia"], precision: 150000, hint: "Território chileno no Pacífico Sul." },
    { title: "Palácio de Versalhes", description: "Símbolo do absolutismo real francês.", lat: 48.8049, lng: 2.1204, tags: ["História", "Europa"], precision: 50000, hint: "Subúrbio de Paris, França." },
    { title: "Mosteiro de Santa Catarina", description: "Um dos mosteiros cristãos mais antigos em funcionamento.", lat: 28.5559, lng: 33.9757, tags: ["História", "África"], precision: 100000, hint: "Pés do Monte Sinai, Egito." },
    { title: "Teotihuacán", description: "Cidade das pirâmides do Sol e da Lua.", lat: 19.6925, lng: -98.8436, tags: ["História", "América"], precision: 120000, hint: "Vale do México, nordeste da Cidade do México." },
    { title: "Chichén Itzá", description: "Cidade maia com a pirâmide de Kukulkan.", lat: 20.6843, lng: -88.5678, tags: ["História", "América"], precision: 100000, hint: "Península de Yucatán, México." },
    { title: "Ruínas de Cartago", description: "Antiga cidade fenícia e rival de Roma.", lat: 36.8529, lng: 10.3233, tags: ["História", "África"], precision: 80000, hint: "Subúrbio de Túnis, Tunísia." },
    { title: "Alhambra", description: "Complexo de palácios e fortalezas da era moura.", lat: 37.1760, lng: -3.5889, tags: ["História", "Europa"], precision: 50000, hint: "Granada, sul da Espanha." },
    { title: "Fórum Romano", description: "Centro da vida pública na Roma Antiga.", lat: 41.8925, lng: 12.4853, tags: ["História", "Europa"], precision: 40000, hint: "Vale entre as colinas Palatino e Capitolino, Roma." },
    { title: "Templo de Karnak", description: "Maior complexo religioso do antigo Egito.", lat: 25.7187, lng: 32.6573, tags: ["História", "África"], precision: 100000, hint: "Luxor, margem leste do Nilo." },
    { title: "Valle de los Caídos", description: "Monumento franquista com uma grande cruz.", lat: 40.6411, lng: -4.1553, tags: ["História", "Europa"], precision: 80000, hint: "Vale na Serra de Guadarrama, Espanha." },
    { title: "Cidade Proibida", description: "Palácio imperial das dinastias Ming e Qing.", lat: 39.9169, lng: 116.3907, tags: ["História", "Ásia"], precision: 60000, hint: "Centro de Pequim, China." },
    { title: "Torre de Londres", description: "Castelo histórico que já foi prisão e zoológico.", lat: 51.5081, lng: -0.0759, tags: ["História", "Europa"], precision: 40000, hint: "Margem norte do rio Tâmisa, Londres." },
    { title: "Basílica de São Pedro", description: "Maior igreja do cristianismo.", lat: 41.9022, lng: 12.4539, tags: ["História", "Europa"], precision: 40000, hint: "Cidade do Vaticano, Roma." },
    { title: "Veneza", description: "Cidade construída sobre canais na laguna.", lat: 45.4408, lng: 12.3155, tags: ["História", "Europa"], precision: 60000, hint: "Nordeste da Itália, mar Adriático." },
    { title: "Persépolis", description: "Capital cerimonial do Império Aquemênida.", lat: 29.9355, lng: 52.8914, tags: ["História", "Ásia"], precision: 120000, hint: "Irã, próximo a Shiraz." },
    { title: "Palácio de Buckingham", description: "Residência oficial do monarca britânico.", lat: 51.5014, lng: -0.1419, tags: ["História", "Europa"], precision: 30000, hint: "Cidade de Westminster, Londres." },
    { title: "Catedral de Notre-Dame", description: "Catedral gótica famosa na Île de la Cité.", lat: 48.8530, lng: 2.3499, tags: ["História", "Europa"], precision: 30000, hint: "Ilha no rio Sena, Paris." },
    { title: "Museu do Louvre", description: "Maior museu de arte do mundo.", lat: 48.8606, lng: 2.3376, tags: ["História", "Europa"], precision: 30000, hint: "Margem direita do Sena, Paris." },

    // ============ ESTRUTURAS E ENGENHARIA (30) ============
    { title: "Torre Eiffel", description: "Torre de ferro símbolo de Paris.", lat: 48.8584, lng: 2.2945, tags: ["Engenharia", "Europa"], precision: 20000, hint: "Campo de Marte, Paris." },
    { title: "Estátua da Liberdade", description: "Símbolo da liberdade presente da França aos EUA.", lat: 40.6892, lng: -74.0445, tags: ["Monumento", "EUA"], precision: 30000, hint: "Ilha da Liberdade, porto de Nova York." },
    { title: "Golden Gate Bridge", description: "Ponte suspensa icônica de São Francisco.", lat: 37.8199, lng: -122.4783, tags: ["Engenharia", "EUA"], precision: 40000, hint: "Conecta São Francisco ao Condado de Marin." },
    { title: "Burj Khalifa", description: "Arranha-céu mais alto do mundo.", lat: 25.1972, lng: 55.2744, tags: ["Engenharia", "Ásia"], precision: 30000, hint: "Downtown Dubai, Emirados Árabes." },
    { title: "Opera House de Sydney", description: "Edifício com telhados em forma de conchas.", lat: -33.8568, lng: 151.2153, tags: ["Arquitetura", "Oceania"], precision: 30000, hint: "Bennelong Point, porto de Sydney." },
    { title: "Ponte da Baía de Hangzhou", description: "Uma das mais longas pontes oceânicas do mundo.", lat: 30.5110, lng: 121.1883, tags: ["Engenharia", "Ásia"], precision: 150000, hint: "Liga Jiaxing a Ningbo, China." },
    { title: "Itaipu Binacional", description: "Uma das maiores usinas hidrelétricas do mundo.", lat: -25.4072, lng: -54.5892, tags: ["Engenharia", "Brasil"], precision: 100000, hint: "Rio Paraná, fronteira Brasil-Paraguai." },
    { title: "Cristo Redentor", description: "Estátua do Cristo no topo do Corcovado.", lat: -22.9519, lng: -43.2106, tags: ["Monumento", "Brasil"], precision: 30000, hint: "Pico do Corcovado, Rio de Janeiro." },
    { title: "Usina de Chernobyl", description: "Local do pior acidente nuclear da história.", lat: 51.3895, lng: 30.0990, tags: ["História", "Europa"], precision: 80000, hint: "Pripyat, norte da Ucrânia." },
    { title: "Ponte Akashi-Kaikyō", description: "Ponte suspensa com o maior vão central do mundo.", lat: 34.6167, lng: 135.0167, tags: ["Engenharia", "Ásia"], precision: 70000, hint: "Conecta Kobe à ilha Awaji, Japão." },
    { title: "Grande Muralha", description: "Muralha defensiva de milhares de quilômetros.", lat: 40.4319, lng: 116.5704, tags: ["Engenharia", "Ásia"], precision: 500000, hint: "Serpenteia pelo norte da China." },
    { title: "Palácio da Cultura e Ciência", description: "Arranha-céu stalinista presente da URSS.", lat: 52.2319, lng: 21.0063, tags: ["Arquitetura", "Europa"], precision: 40000, hint: "Centro de Varsóvia, Polônia." },
    { title: "Atomium", description: "Estrutura de átomos ampliados símbolo de Bruxelas.", lat: 50.8949, lng: 4.3416, tags: ["Arquitetura", "Europa"], precision: 30000, hint: "Bruxelas, Bélgica." },
    { title: "Ponte 25 de Abril", description: "Ponte suspensa sobre o rio Tejo.", lat: 38.6920, lng: -9.1774, tags: ["Engenharia", "Europa"], precision: 40000, hint: "Liga Lisboa a Almada, Portugal." },
    { title: "Ponte do Brooklyn", description: "Ponte suspensa histórica de Nova York.", lat: 40.7061, lng: -73.9969, tags: ["Engenharia", "EUA"], precision: 30000, hint: "Conecta Manhattan ao Brooklyn." },
    { title: "Ponte da Baía de Sydney", description: "Ponte de arco de aço icônica.", lat: -33.8523, lng: 151.2108, tags: ["Engenharia", "Oceania"], precision: 40000, hint: "Conecta o centro ao norte de Sydney." },
    { title: "Suez", description: "Canal marítimo que liga o Mediterrâneo ao Mar Vermelho.", lat: 30.5852, lng: 32.2654, tags: ["Logística", "África"], precision: 300000, hint: "Egito, através do istmo de Suez." },
    { title: "Ponte de Rialto", description: "Ponte de pedra sobre o Grande Canal.", lat: 45.4380, lng: 12.3360, tags: ["História", "Europa"], precision: 20000, hint: "Veneza, Itália." },
    { title: "Petronas Towers", description: "Torres gêmeas que já foram as mais altas do mundo.", lat: 3.1579, lng: 101.7116, tags: ["Arquitetura", "Ásia"], precision: 40000, hint: "Kuala Lumpur, Malásia." },
    { title: "Catedral de São Basílio", description: "Catedral com cúpulas coloridas em forma de bulbo.", lat: 55.7525, lng: 37.6231, tags: ["Arquitetura", "Europa"], precision: 30000, hint: "Praça Vermelha, Moscou." },
    { title: "CN Tower", description: "Torre de comunicações símbolo de Toronto.", lat: 43.6426, lng: -79.3871, tags: ["Engenharia", "América"], precision: 40000, hint: "Toronto, Ontário, Canadá." },
    { title: "Space Needle", description: "Torre de observação futurista.", lat: 47.6205, lng: -122.3493, tags: ["Arquitetura", "EUA"], precision: 30000, hint: "Seattle, Washington, EUA." },
    { title: "Big Ben", description: "Torre do relógio do Palácio de Westminster.", lat: 51.5007, lng: -0.1246, tags: ["Monumento", "Europa"], precision: 30000, hint: "Londres, Reino Unido." },
    { title: "Ponte de Millau", description: "Ponte rodoviária mais alta do mundo.", lat: 44.0775, lng: 3.0228, tags: ["Engenharia", "Europa"], precision: 80000, hint: "Vale do Tarn, sul da França." },
    { title: "Marina Bay Sands", description: "Complexo com piscina infinita no topo.", lat: 1.2838, lng: 103.8585, tags: ["Arquitetura", "Ásia"], precision: 40000, hint: "Cingapura." },
    { title: "Gateway Arch", description: "Arco monumental de aço inoxidável.", lat: 38.6247, lng: -90.1848, tags: ["Monumento", "EUA"], precision: 40000, hint: "St. Louis, Missouri, EUA." },
    { title: "Sagrada Família", description: "Templo expiatório de Gaudí em construção.", lat: 41.4036, lng: 2.1744, tags: ["Arquitetura", "Europa"], precision: 30000, hint: "Barcelona, Espanha." },
    { title: "Colosso de Rodes", description: "Local da antiga estátua gigante do deus Hélios.", lat: 36.4511, lng: 28.2278, tags: ["História", "Europa"], precision: 50000, hint: "Porto de Rodes, Grécia." },
    { title: "Torre de Pisa", description: "Campanário inclinado devido à fundação instável.", lat: 43.7230, lng: 10.3966, tags: ["Arquitetura", "Europa"], precision: 30000, hint: "Piazza dei Miracoli, Pisa, Itália." },
    { title: "Ópera de Oslo", description: "Edifício de mármore branco que parece um iceberg.", lat: 59.9076, lng: 10.7533, tags: ["Arquitetura", "Europa"], precision: 30000, hint: "Fiorde de Oslo, Noruega." },

    // ============ REGIÕES E PAÍSES (30) ============
    { title: "Sibéria", description: "Vasta região da Rússia conhecida pelo frio extremo.", lat: 61.0, lng: 105.0, tags: ["Região", "Rússia"], precision: 1500000, hint: "Ásia setentrional, norte da Rússia." },
    { title: "Patagônia", description: "Região compartilhada pela Argentina e Chile.", lat: -41.8, lng: -68.9, tags: ["Região", "América"], precision: 800000, hint: "Extremo sul da América do Sul." },
    { title: "Escandinávia", description: "Região que inclui Noruega, Suécia e Dinamarca.", lat: 62.0, lng: 15.0, tags: ["Região", "Europa"], precision: 1000000, hint: "Península no norte da Europa." },
    { title: "Península Arábica", description: "Maior península do mundo, rica em petróleo.", lat: 23.0, lng: 46.0, tags: ["Região", "Ásia"], precision: 1200000, hint: "Sudoeste da Ásia." },
    { title: "Bálcãs", description: "Região montanhosa no sudeste da Europa.", lat: 44.0, lng: 21.0, tags: ["Região", "Europa"], precision: 800000, hint: "Península dos Bálcãs." },
    { title: "Andes", description: "A mais longa cadeia de montanhas continentais.", lat: -32.0, lng: -70.0, tags: ["Relevo", "América"], precision: 2000000, hint: "Costa oeste da América do Sul." },
    { title: "Alpes", description: "Principal cordilheira da Europa Central.", lat: 46.5, lng: 10.0, tags: ["Relevo", "Europa"], precision: 500000, hint: "Centro-sul da Europa." },
    { title: "Cáucaso", description: "Região montanhosa entre o mar Negro e o Cáspio.", lat: 42.0, lng: 45.0, tags: ["Região", "Ásia"], precision: 600000, hint: "Fronteira Rússia/Geórgia/Armênia." },
    { title: "Indochina", description: "Península no sudeste asiático.", lat: 16.0, lng: 102.0, tags: ["Região", "Ásia"], precision: 900000, hint: "Entre Índia e China, inclui Tailândia, Vietnã." },
    { title: "Magrebe", description: "Região do noroeste da África.", lat: 31.0, lng: -7.0, tags: ["Região", "África"], precision: 800000, hint: "Inclui Marrocos, Argélia, Tunísia." },
    { title: "Cornualha", description: "Península no sudoeste da Inglaterra.", lat: 50.3, lng: -5.0, tags: ["Região", "Europa"], precision: 200000, hint: "Extremo sudoeste da Grã-Bretanha." },
    { title: "Lapônia", description: "Região ártica que abrange partes de Noruega, Suécia, Finlândia e Rússia.", lat: 67.9, lng: 26.0, tags: ["Região", "Europa"], precision: 800000, hint: "Círculo Polar Ártico, norte da Escandinávia." },
    { title: "Transilvânia", description: "Região histórica na Romênia, famosa pelo Drácula.", lat: 46.8, lng: 23.6, tags: ["Região", "Europa"], precision: 300000, hint: "Central na Romênia, cercada pelos Cárpatos." },
    { title: "Cárpatos", description: "Cadeia montanhosa na Europa Oriental.", lat: 47.0, lng: 25.5, tags: ["Relevo", "Europa"], precision: 700000, hint: "Forma um arco através da Romênia, Ucrânia, etc." },
    { title: "Urais", description: "Cadeia montanhosa que divide Europa e Ásia.", lat: 60.0, lng: 60.0, tags: ["Relevo", "Rússia"], precision: 1000000, hint: "Rússia, de norte a sul." },
    { title: "Mesoamérica", description: "Região histórica que inclui civilizações pré-colombianas.", lat: 19.0, lng: -99.0, tags: ["História", "América"], precision: 800000, hint: "Do centro do México à Costa Rica." },
    { title: "Cinturão de Fogo do Pacífico", description: "Zona de terremotos e vulcões ao redor do Pacífico.", lat: 0.0, lng: -170.0, tags: ["Sismo", "Global"], precision: 3000000, hint: "Anel ao redor da bacia do Oceano Pacífico." },
    { title: "Sahel", description: "Faixa de transição entre o Saara e as savanas.", lat: 15.0, lng: 20.0, tags: ["Região", "África"], precision: 1500000, hint: "Norte da África, sul do Saara." },
    { title: "Cerrado", description: "Savana brasileira com grande biodiversidade.", lat: -15.0, lng: -47.0, tags: ["Bio", "Brasil"], precision: 800000, hint: "Centro-oeste do Brasil." },
    { title: "Mata Atlântica", description: "Floresta tropical úmida na costa brasileira.", lat: -23.5, lng: -45.0, tags: ["Bio", "Brasil"], precision: 1000000, hint: "Costa leste do Brasil." },
    { title: "Pampas", description: "Planícies férteis na Argentina e Uruguai.", lat: -35.0, lng: -62.0, tags: ["Região", "América"], precision: 700000, hint: "Centro-leste da Argentina." },
    { title: "Grande Lago Salgado", description: "Maior lago de água salgada no hemisfério ocidental.", lat: 41.1, lng: -112.4, tags: ["Lago", "EUA"], precision: 150000, hint: "Utah, EUA." },
    { title: "Delta do Mekong", description: "Região extremamente fértil no sul do Vietnã.", lat: 10.0, lng: 105.8, tags: ["Região", "Ásia"], precision: 300000, hint: "Extremo sul do Vietnã." },
    { title: "Grande Vale do Rift", description: "Vale de falha geológica na África Oriental.", lat: 1.0, lng: 36.0, tags: ["Geologia", "África"], precision: 1500000, hint: "Do Moçambique à Jordânia." },
    { title: "Ilhas Canárias", description: "Arquipélago espanhol no Atlântico, próximo à África.", lat: 28.3, lng: -16.6, tags: ["Região", "Europa"], precision: 300000, hint: "A oeste de Marrocos." },
    { title: "Ilhas Malvinas/Falklands", description: "Arquipélago no Atlântico Sul, disputado.", lat: -51.7963, lng: -59.5236, tags: ["Região", "América"], precision: 200000, hint: "Sudeste da Argentina." },
    { title: "Groenlândia", description: "Maior ilha do mundo, território autônomo dinamarquês.", lat: 71.7069, lng: -42.6043, tags: ["Região", "América"], precision: 1500000, hint: "Entre o Atlântico Norte e o Oceano Ártico." },
    { title: "Antártida", description: "Continente mais frio, seco e ventoso.", lat: -82.8628, lng: 135.0, tags: ["Região", "Polar"], precision: 5000000, hint: "Polo Sul." },
    { title: "Triângulo das Bermudas", description: "Área no Atlântico com lendas de desaparecimentos.", lat: 25.0, lng: -71.0, tags: ["Mistério", "Oceano"], precision: 1000000, hint: "Entre Bermudas, Flórida e Porto Rico." },
    { title: "Micronésia", description: "Sub-região da Oceania com milhares de pequenas ilhas.", lat: 6.8874, lng: 158.2150, tags: ["Região", "Oceania"], precision: 1500000, hint: "Oceano Pacífico ocidental." },

    // ============ CIDADES IMPORTANTES (NÃO CAPITAIS) (30) ============
    { title: "Nova York", description: "Maior cidade dos EUA, centro financeiro global.", lat: 40.7128, lng: -74.0060, tags: ["Cidade", "EUA"], precision: 50000, hint: "Costa leste, estado de Nova York." },
    { title: "Los Angeles", description: "Centro da indústria do cinema e da TV.", lat: 34.0522, lng: -118.2437, tags: ["Cidade", "EUA"], precision: 80000, hint: "Sul da Califórnia." },
    { title: "Chicago", description: "Cidade dos ventos, centro ferroviário dos EUA.", lat: 41.8781, lng: -87.6298, tags: ["Cidade", "EUA"], precision: 70000, hint: "Margem do lago Michigan, Illinois." },
    { title: "São Paulo", description: "Maior metrópole do hemisfério sul.", lat: -23.5505, lng: -46.6333, tags: ["Cidade", "Brasil"], precision: 60000, hint: "Sudeste do Brasil, planalto." },
    { title: "Rio de Janeiro", description: "Cidade maravilhosa entre montanhas e mar.", lat: -22.9068, lng: -43.1729, tags: ["Cidade", "Brasil"], precision: 60000, hint: "Costa sudeste brasileira." },
    { title: "Mumbai", description: "Capital financeira e do cinema da Índia.", lat: 19.0760, lng: 72.8777, tags: ["Cidade", "Ásia"], precision: 70000, hint: "Costa oeste da Índia." },
    { title: "Xangai", description: "Maior cidade e porto da China.", lat: 31.2304, lng: 121.4737, tags: ["Cidade", "Ásia"], precision: 70000, hint: "Delta do rio Yangtzé, costa leste." },
    { title: "Hong Kong", description: "Região administrativa especial da China, centro financeiro.", lat: 22.3193, lng: 114.1694, tags: ["Cidade", "Ásia"], precision: 50000, hint: "Costa sul da China, delta do Rio das Pérolas." },
    { title: "Singapura", description: "Cidade-Estado e centro financeiro global.", lat: 1.3521, lng: 103.8198, tags: ["Cidade", "Ásia"], precision: 40000, hint: "Extremo sul da Península Malaia." },
    { title: "Dubai", description: "Cidade dos Emirados Árabes famosa por arranha-céus.", lat: 25.2048, lng: 55.2708, tags: ["Cidade", "Ásia"], precision: 60000, hint: "Costa do Golfo Pérsico." },
    { title: "São Petersburgo", description: "Segunda maior cidade da Rússia, histórica capital imperial.", lat: 59.9343, lng: 30.3351, tags: ["Cidade", "Rússia"], precision: 60000, hint: "Foz do rio Neva, golfo da Finlândia." },
    { title: "Istanbul", description: "Cidade transcontinental entre a Europa e a Ásia.", lat: 41.0082, lng: 28.9784, tags: ["Cidade", "Ásia"], precision: 70000, hint: "Estreito de Bósforo, Turquia." },
    { title: "Barcelona", description: "Cidade da Catalunha famosa pela arquitetura de Gaudí.", lat: 41.3851, lng: 2.1734, tags: ["Cidade", "Europa"], precision: 50000, hint: "Costa nordeste da Espanha." },
    { title: "Milão", description: "Capital da moda e design da Itália.", lat: 45.4642, lng: 9.1900, tags: ["Cidade", "Europa"], precision: 50000, hint: "Norte da Itália, planície da Lombardia." },
    { title: "Frankfurt", description: "Centro financeiro da Alemanha e da União Europeia.", lat: 50.1109, lng: 8.6821, tags: ["Cidade", "Europa"], precision: 50000, hint: "Centro da Alemanha, estado de Hesse." },
    { title: "Manchester", description: "Berço da Revolução Industrial.", lat: 53.4808, lng: -2.2426, tags: ["Cidade", "Europa"], precision: 50000, hint: "Noroeste da Inglaterra." },
    { title: "Johanesburgo", description: "Maior cidade da África do Sul, centro econômico.", lat: -26.2041, lng: 28.0473, tags: ["Cidade", "África"], precision: 70000, hint: "Província de Gauteng, interior." },
    { title: "Casablanca", description: "Maior cidade do Marrocos, porto importante.", lat: 33.5731, lng: -7.5898, tags: ["Cidade", "África"], precision: 60000, hint: "Costa atlântica do Marrocos." },
    { title: "Lagos", description: "Maior cidade da Nigéria e da África.", lat: 6.5244, lng: 3.3792, tags: ["Cidade", "África"], precision: 80000, hint: "Costa sudoeste da Nigéria, golfo da Guiné." },
    { title: "Melbourne", description: "Capital cultural e esportiva da Austrália.", lat: -37.8136, lng: 144.9631, tags: ["Cidade", "Oceania"], precision: 60000, hint: "Sudeste da Austrália, estado de Victoria." },
    { title: "Auckland", description: "Maior cidade da Nova Zelândia.", lat: -36.8485, lng: 174.7633, tags: ["Cidade", "Oceania"], precision: 60000, hint: "Ilha do Norte, Nova Zelândia." },
    { title: "Vancouver", description: "Cidade portuária no oeste do Canadá.", lat: 49.2827, lng: -123.1207, tags: ["Cidade", "América"], precision: 50000, hint: "Costa do Pacífico, Colúmbia Britânica." },
    { title: "Guadalajara", description: "Segunda maior cidade do México, berço do mariachi.", lat: 20.6597, lng: -103.3496, tags: ["Cidade", "América"], precision: 70000, hint: "Oeste do México, estado de Jalisco." },
    { title: "Medellín", description: "Cidade da eterna primavera na Colômbia.", lat: 6.2442, lng: -75.5812, tags: ["Cidade", "América"], precision: 60000, hint: "Vale de Aburrá, Cordilheira Central dos Andes." },
    { title: "Lima", description: "Capital e maior cidade do Peru.", lat: -12.0464, lng: -77.0428, tags: ["Cidade", "América"], precision: 80000, hint: "Costa central do Peru." },
    { title: "Bangkok", description: "Capital e centro urbano da Tailândia.", lat: 13.7563, lng: 100.5018, tags: ["Cidade", "Ásia"], precision: 70000, hint: "Delta do rio Chao Phraya." },
    { title: "Bangalore", description: "Capital indiana da tecnologia da informação.", lat: 12.9716, lng: 77.5946, tags: ["Cidade", "Ásia"], precision: 70000, hint: "Planalto do Decã, sul da Índia." },
    { title: "Cidade do Cabo", description: "Cidade portuária na ponta sul da África.", lat: -33.9249, lng: 18.4241, tags: ["Cidade", "África"], precision: 60000, hint: "Costa sudoeste, Cabo da Boa Esperança." },
    { title: "Nairóbi", description: "Capital do Quênia e centro da África Oriental.", lat: -1.2864, lng: 36.8172, tags: ["Cidade", "África"], precision: 70000, hint: "Terras altas do Quênia." },
    { title: "Tel Aviv", description: "Centro financeiro e tecnológico de Israel.", lat: 32.0853, lng: 34.7818, tags: ["Cidade", "Ásia"], precision: 50000, hint: "Costa mediterrânea de Israel." },

    // ============ BAHIA (MAIS 16 PARA COMPLEMENTAR) ============
    { title: "Juazeiro", description: "Terra das frutas irrigadas pelo Rio São Francisco.", lat: -9.4117, lng: -40.5025, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Extremo norte da Bahia, fronteira com Pernambuco." },
    { title: "Barreiras", description: "Coroas do Oeste Baiano, celeiro agrícola.", lat: -12.1520, lng: -44.9910, tags: ["Bahia", "Brasil"], precision: 60000, hint: "Oeste da Bahia." },
    { title: "Lauro de Freitas", description: "Cidade metropolitana próxima a Salvador.", lat: -12.8944, lng: -38.3272, tags: ["Bahia", "Brasil"], precision: 30000, hint: "Região Metropolitana de Salvador." },
    { title: "Camaçari", description: "Maior polo petroquímico da América Latina.", lat: -12.6994, lng: -38.3236, tags: ["Bahia", "Industrial"], precision: 40000, hint: "Região Metropolitana de Salvador." },
    { title: "Eunápolis", description: "Portal sul da Bahia, próximo a Porto Seguro.", lat: -16.3715, lng: -39.5800, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Extremo sul da Bahia." },
    { title: "Jequié", description: "Capital regional do centro-sul baiano.", lat: -13.8588, lng: -40.0851, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Centro-sul da Bahia." },
    { title: "Santo Antônio de Jesus", description: "Maior centro comercial do Recôncavo Baiano.", lat: -12.9683, lng: -39.2614, tags: ["Bahia", "Brasil"], precision: 40000, hint: "Recôncavo Baiano." },
    { title: "Alagoinhas", description: "Importante entroncamento ferroviário.", lat: -12.1404, lng: -38.4245, tags: ["Bahia", "Logística"], precision: 45000, hint: "Nordeste da Bahia." },
    { title: "Teixeira de Freitas", description: "Maior cidade do extremo sul baiano.", lat: -17.5347, lng: -39.7419, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Extremo sul da Bahia." },
    { title: "Paulo Afonso", description: "Cidade das cataratas e da hidrelétrica do São Francisco.", lat: -9.4062, lng: -38.2199, tags: ["Bahia", "Energia"], precision: 60000, hint: "Nordeste da Bahia, divisa com Alagoas e Sergipe." },
    { title: "Guanambi", description: "Terra da energia solar e do feijão.", lat: -14.2231, lng: -42.7794, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Sudoeste da Bahia." },
    { title: "Bom Jesus da Lapa", description: "Maior centro de romaria do norte da Bahia.", lat: -13.2550, lng: -43.4181, tags: ["Bahia", "Religião"], precision: 60000, hint: "Vale do São Francisco, oeste da Bahia." },
    { title: "Valença", description: "Cidade histórica no Recôncavo, famosa pelo dendê.", lat: -13.3669, lng: -39.0714, tags: ["Bahia", "História"], precision: 40000, hint: "Recôncavo Baiano, margem do rio Una." },
    { title: "Senhor do Bonfim", description: "Portal do sertão norte, famosa pela fé.", lat: -10.4634, lng: -40.1894, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Centro-norte da Bahia." },
    { title: "Itabuna", description: "Maior cidade do sul da Bahia, terra do cacau.", lat: -14.7874, lng: -39.2781, tags: ["Bahia", "Brasil"], precision: 45000, hint: "Sul da Bahia, próxima a Ilhéus." },
    { title: "Irecê", description: "Capital da Bacia do Irecê, região agrícola.", lat: -11.3039, lng: -41.8561, tags: ["Bahia", "Brasil"], precision: 50000, hint: "Centro-norte da Bahia, chapada." },

    // ============ RIO SÃO FRANCISCO (10) ============
    { title: "Nascente do São Francisco", description: "O Velho Chico nasce na Serra da Canastra.", lat: -20.2411, lng: -46.3697, tags: ["Rio", "Brasil"], precision: 150000, hint: "Minas Gerais, Parque Nacional da Serra da Canastra." },
    { title: "Três Marias", description: "Maior lago artificial do mundo em volume na época de sua construção.", lat: -18.2158, lng: -45.2514, tags: ["Hidrelétrica", "Brasil"], precision: 120000, hint: "Centro de Minas Gerais, represa no São Francisco." },
    { title: "Pirapora", description: "Porto histórico e início da navegação regular.", lat: -17.3450, lng: -44.9425, tags: ["Rio", "Brasil"], precision: 80000, hint: "Norte de Minas Gerais." },
    { title: "Januária", description: "Terra das veredas e dos buritis.", lat: -15.4880, lng: -44.3639, tags: ["Rio", "Brasil"], precision: 90000, hint: "Norte de Minas Gerais, margem do São Francisco." },
    { title: "Xique-Xique", description: "Cidade ilha no coração do São Francisco.", lat: -10.8231, lng: -42.7300, tags: ["Rio", "Brasil"], precision: 100000, hint: "Bahia, no meio do rio." },
    { title: "Barra", description: "Onde o Rio Grande e o São Francisco se encontram.", lat: -11.0889, lng: -43.1417, tags: ["Rio", "Brasil"], precision: 100000, hint: "Oeste da Bahia, confluência de rios." },
    { title: "Juazeiro/Petrolina", description: "Gêmeas do São Francisco, polo de fruticultura irrigada.", lat: -9.4164, lng: -40.5025, tags: ["Rio", "Brasil"], precision: 80000, hint: "Fronteira Bahia/Pernambuco." },
    { title: "Cachoeira de Paulo Afonso", description: "Quedas d'água que alimentam um complexo hidrelétrico.", lat: -9.3936, lng: -38.2239, tags: ["Hidrelétrica", "Brasil"], precision: 120000, hint: "Divisa Bahia/Alagoas." },
    { title: "Penedo", description: "Cidade histórica alagoana às margens do São Francisco.", lat: -10.2904, lng: -36.5861, tags: ["Rio", "Brasil"], precision: 70000, hint: "Alagoas, próximo à foz." },
    { title: "Foz do São Francisco", description: "Onde o Velho Chico encontra o Oceano Atlântico.", lat: -10.5026, lng: -36.3947, tags: ["Rio", "Brasil"], precision: 150000, hint: "Divisa Alagoas/Sergipe." },

    // ============ FENÔMENOS E DESASTRES NATURAIS (10) ============
    { title: "Tsunami do Oceano Índico (2004)", description: "Um dos piores desastres naturais da história.", lat: 3.3167, lng: 95.8544, tags: ["Desastre", "Ásia"], precision: 500000, hint: "Epicentro ao largo da costa de Sumatra, Indonésia." },
    { title: "Furacão Katrina", description: "Furacão que devastou Nova Orleans.", lat: 29.9511, lng: -90.0715, tags: ["Desastre", "EUA"], precision: 200000, hint: "Golfo do México, Louisiana, EUA." },
    { title: "Erupção do Vesúvio (79 d.C.)", description: "Destruiu Pompeia e Herculano.", lat: 40.8210, lng: 14.4260, tags: ["Vulcão", "Europa"], precision: 80000, hint: "Golfo de Nápoles, Itália." },
    { title: "Terremoto do Haiti (2010)", description: "Terremoto catastrófico de magnitude 7.0.", lat: 18.4434, lng: -72.5716, tags: ["Sismo", "América"], precision: 150000, hint: "Próximo a Porto Príncipe, Haiti." },
    { title: "Fukushima Daiichi", description: "Usina nuclear afetada por tsunami em 2011.", lat: 37.4213, lng: 141.0328, tags: ["Desastre", "Ásia"], precision: 80000, hint: "Costa leste de Honshu, Japão." },
    { title: "Inundação do Rio Yangtzé (1931)", description: "Uma das piores enchentes da história.", lat: 30.6, lng: 114.3, tags: ["Desastre", "Ásia"], precision: 300000, hint: "Bacia do rio Yangtzé, China." },
    { title: "Erupção do Monte Santa Helena", description: "Erupção vulcânica catastrófica em 1980.", lat: 46.1912, lng: -122.1944, tags: ["Vulcão", "EUA"], precision: 120000, hint: "Estado de Washington, EUA." },
    { title: "Ciclone Nargis", description: "Ciclone que atingiu Mianmar em 2008.", lat: 16.0, lng: 96.0, tags: ["Desastre", "Ásia"], precision: 400000, hint: "Delta do Irrawaddy, Mianmar." },
    { title: "Terremoto de Valdivia", description: "O mais potente terremoto já registrado (1960).", lat: -38.2397, lng: -73.0479, tags: ["Sismo", "América"], precision: 200000, hint: "Sul do Chile." },
    { title: "Seca do Sahel", description: "Secas recorrentes que causam fome na África.", lat: 15.0, lng: 0.0, tags: ["Desastre", "África"], precision: 1500000, hint: "Faixa do Sahel, norte da África." },

    // ============ ESTAÇÕES ECLÉTICAS FINAIS (10 para completar 300) ============
    { title: "Polo Norte Geográfico", description: "Ponto mais ao norte do eixo de rotação da Terra.", lat: 90.0, lng: 0.0, tags: ["Polar", "Global"], precision: 1000000, hint: "Meio do Oceano Ártico, gelo marinho." },
    { title: "Polo Sul Geográfico", description: "Ponto mais ao sul do eixo de rotação da Terra.", lat: -90.0, lng: 0.0, tags: ["Polar", "Global"], precision: 1000000, hint: "Continente Antártico." },
    { title: "Mar Morto", description: "O ponto mais baixo da superfície terrestre, com água supersalgada.", lat: 31.5590, lng: 35.4732, tags: ["Geologia", "Ásia"], precision: 150000, hint: "Fronteira Jordânia/Israel." },
    { title: "Lago Vostok", description: "Maior lago subglacial da Antártida, isolado por milhões de anos.", lat: -77.5, lng: 106.0, tags: ["Lago", "Polar"], precision: 300000, hint: "Antártida Oriental, sob o gelo." },
    { title: "Buraco Azul de Dean", description: "O buraco azul mais profundo do mundo.", lat: 25.0, lng: -77.35, tags: ["Natureza", "Bahamas"], precision: 80000, hint: "Baía de Clarence, Bahamas." },
    { title: "Fossa das Marianas", description: "O ponto mais profundo dos oceanos.", lat: 11.35, lng: 142.1999, tags: ["Oceano", "Global"], precision: 300000, hint: "Oeste do Oceano Pacífico, leste das Filipinas." },
    { title: "Círculo Polar Ártico", description: "Linha de latitude onde o sol não se põe no solstício de verão.", lat: 66.5636, lng: 0.0, tags: ["Carto", "Global"], precision: 1000000, hint: "Círculo ao redor do Polo Norte." },
    { title: "Trópico de Câncer", description: "Linha de latitude mais ao norte onde o sol pode estar diretamente sobrecarga.", lat: 23.4368, lng: 0.0, tags: ["Carto", "Global"], precision: 1000000, hint: "Atravessa México, Saara, Arábia, Índia, China." },
    { title: "Trópico de Capricórnio", description: "Linha de latitude mais ao sul onde o sol pode estar diretamente sobrecarga.", lat: -23.4368, lng: 0.0, tags: ["Carto", "Global"], precision: 1000000, hint: "Atravessa Chile, Argentina, Paraguai, Brasil, Austrália." },
    { title: "Linha do Equador", description: "Linha imaginária que divide a Terra em hemisférios norte e sul.", lat: 0.0, lng: -78.4678, tags: ["Carto", "Global"], precision: 1000000, hint: "Passa pelo Equador, Quito, Brasil, Congo, Indonésia." }
];
